services:
  - type: web
    name: zoryx-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.1.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
